<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="M_PI" value="3.1415926" />
    
    <xacro:property name="base_length" value="0.16" />
    <xacro:property name="base_radius" value="0.20" />

    <xacro:property name="wheel_length" value="0.03" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_joint_y" value="0.19" />
    <xacro:property name="wheel_joint_z" value="0.07" />

    <xacro:property name="caster_joint_x" value="0.18" />
    <xacro:property name="caster_radius" value="0.015" />
    <xacro:property name="caster_box_size" value="0.01" />

    <material name="yellow">
        <color rgba="1 0.4 0 1" />
    </material>
    <material name="black">
        <color rgba="0 0 0 0.95" />
    </material>
    <material name="blue">
        <color rgba="0 0 1 1" />
    </material>
    <material name="gray">
        <color rgba="0.75 0.75 0.75 0.95" />
    </material>

    <xacro:macro name="wheel" params="prefix reflect">
        <joint name="${prefix}_wheel_joint" type="continuous">
            <origin xyz="0 ${reflect*wheel_joint_y} ${-wheel_joint_z}" rpy="0 0 0"/>
            <parent link="base_link" />
            <child link="${prefix}_wheel_link" />
            <axis xyz="0 1 0" />
        </joint>
        <link name="${prefix}_wheel_link">
            <visual>
                <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder length="${wheel_length}" radius="${wheel_radius}" />
                </geometry>
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>
 
    <xacro:macro name="caster" params="prefix reflect">
        <joint name="${prefix}_caster_box_base_joint" type="fixed">
            <origin xyz="${reflect*caster_joint_x} 0 ${-(caster_box_size/2 + base_length/2)}" rpy="0 0 0" />
            <parent link="base_link" />
            <child link="${prefix}_caster_box" />
        </joint>
        <link name="${prefix}_caster_box">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="${caster_box_size} ${caster_box_size} ${caster_box_size}" rpy="0 0 0" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
        <joint name="${prefix}_caster_joint" type="continuous">
            <origin xyz="0 0 ${-(caster_box_size/2 + caster_radius/2)}" rpy="0 0 0" />
            <parent link="${prefix}_caster_box" />
            <child link="${prefix}_caster_link" />
            <axis xyz="0 1 0" />
        </joint>
        <link name="${prefix}_caster_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <sphere radius="${caster_radius}" />
                </geometry>
                <material name="black" />
            </visual>
        </link>
    </xacro:macro>

    <xacro:macro name="my_robot_base">
        <link name="base_footprint">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <box size="0.001 0.001 0.001" />
                </geometry>
            </visual>
        </link>
        <joint name="base_footprint" type="fixed">
            <origin xyz="0 0 ${caster_box_size*2 + caster_radius*2 + base_length/2}" rpy="0 0 0" />
            <parent link="base_footprint" />
            <child link="base_link" />
        </joint>
        <link name="base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${base_length}" radius="${base_radius}" />
                </geometry>
                <material name="blue"/>
            </visual>
        </link>

        <wheel prefix="left" reflect="-1" />
        <wheel prefix="right" reflect="1" />

        <caster prefix="front" reflect="-1" />
        <caster prefix="back" reflect="1" />
    </xacro:macro>
</robot>