// Auto-generated. Do not edit!

// (in-package self_learning_communication.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class motion_planningGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.final = null;
    }
    else {
      if (initObj.hasOwnProperty('final')) {
        this.final = initObj.final
      }
      else {
        this.final = new geometry_msgs.msg.Vector3();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type motion_planningGoal
    // Serialize message field [final]
    bufferOffset = geometry_msgs.msg.Vector3.serialize(obj.final, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type motion_planningGoal
    let len;
    let data = new motion_planningGoal(null);
    // Deserialize message field [final]
    data.final = geometry_msgs.msg.Vector3.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 24;
  }

  static datatype() {
    // Returns string type for a message object
    return 'self_learning_communication/motion_planningGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '96b55ae3c29c08040f01a834ea1b83ab';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # 定义目标点
    geometry_msgs/Vector3 final
    
    ================================================================================
    MSG: geometry_msgs/Vector3
    # This represents a vector in free space. 
    # It is only meant to represent a direction. Therefore, it does not
    # make sense to apply a translation to it (e.g., when applying a 
    # generic rigid transformation to a Vector3, tf2 will only apply the
    # rotation). If you want your data to be translatable too, use the
    # geometry_msgs/Point message instead.
    
    float64 x
    float64 y
    float64 z
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new motion_planningGoal(null);
    if (msg.final !== undefined) {
      resolved.final = geometry_msgs.msg.Vector3.Resolve(msg.final)
    }
    else {
      resolved.final = new geometry_msgs.msg.Vector3()
    }

    return resolved;
    }
};

module.exports = motion_planningGoal;
