// Auto-generated. Do not edit!

// (in-package self_learning_communication.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class motion_planningResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result = null;
    }
    else {
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = new std_msgs.msg.Bool();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type motion_planningResult
    // Serialize message field [result]
    bufferOffset = std_msgs.msg.Bool.serialize(obj.result, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type motion_planningResult
    let len;
    let data = new motion_planningResult(null);
    // Deserialize message field [result]
    data.result = std_msgs.msg.Bool.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'self_learning_communication/motion_planningResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'c2420602a83d8ccc0f3664e0daafab6c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # 运行结果
    std_msgs/Bool result 
    
    ================================================================================
    MSG: std_msgs/Bool
    bool data
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new motion_planningResult(null);
    if (msg.result !== undefined) {
      resolved.result = std_msgs.msg.Bool.Resolve(msg.result)
    }
    else {
      resolved.result = new std_msgs.msg.Bool()
    }

    return resolved;
    }
};

module.exports = motion_planningResult;
