// Auto-generated. Do not edit!

// (in-package self_learning_communication.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class motion_planningFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.percent = null;
    }
    else {
      if (initObj.hasOwnProperty('percent')) {
        this.percent = initObj.percent
      }
      else {
        this.percent = new std_msgs.msg.Float64();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type motion_planningFeedback
    // Serialize message field [percent]
    bufferOffset = std_msgs.msg.Float64.serialize(obj.percent, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type motion_planningFeedback
    let len;
    let data = new motion_planningFeedback(null);
    // Deserialize message field [percent]
    data.percent = std_msgs.msg.Float64.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'self_learning_communication/motion_planningFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '2023e8040621affdd0459e82a77abec5';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # 不断反馈进度
    std_msgs/Float64 percent
    
    
    ================================================================================
    MSG: std_msgs/Float64
    float64 data
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new motion_planningFeedback(null);
    if (msg.percent !== undefined) {
      resolved.percent = std_msgs.msg.Float64.Resolve(msg.percent)
    }
    else {
      resolved.percent = new std_msgs.msg.Float64()
    }

    return resolved;
    }
};

module.exports = motion_planningFeedback;
