// Generated by gencpp from file self_learning_communication/pose.msg
// DO NOT EDIT!


#ifndef SELF_LEARNING_COMMUNICATION_MESSAGE_POSE_H
#define SELF_LEARNING_COMMUNICATION_MESSAGE_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Int32.h>
#include <std_msgs/Time.h>
#include <geometry_msgs/Pose.h>

namespace self_learning_communication
{
template <class ContainerAllocator>
struct pose_
{
  typedef pose_<ContainerAllocator> Type;

  pose_()
    : camera_id()
    , camera_timestamp()
    , camera_pose()  {
    }
  pose_(const ContainerAllocator& _alloc)
    : camera_id(_alloc)
    , camera_timestamp(_alloc)
    , camera_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Int32_<ContainerAllocator>  _camera_id_type;
  _camera_id_type camera_id;

   typedef  ::std_msgs::Time_<ContainerAllocator>  _camera_timestamp_type;
  _camera_timestamp_type camera_timestamp;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _camera_pose_type;
  _camera_pose_type camera_pose;





  typedef boost::shared_ptr< ::self_learning_communication::pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::self_learning_communication::pose_<ContainerAllocator> const> ConstPtr;

}; // struct pose_

typedef ::self_learning_communication::pose_<std::allocator<void> > pose;

typedef boost::shared_ptr< ::self_learning_communication::pose > posePtr;
typedef boost::shared_ptr< ::self_learning_communication::pose const> poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::self_learning_communication::pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::self_learning_communication::pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace self_learning_communication

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'self_learning_communication': ['/home/xiaoc/xiaoc/code/ros_practice/src/self_learning_communication/msg', '/home/xiaoc/xiaoc/code/ros_practice/devel/share/self_learning_communication/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::self_learning_communication::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::self_learning_communication::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::self_learning_communication::pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::self_learning_communication::pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::self_learning_communication::pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::self_learning_communication::pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::self_learning_communication::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54e782714e2aeb791673a0a14332f140";
  }

  static const char* value(const ::self_learning_communication::pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54e782714e2aeb79ULL;
  static const uint64_t static_value2 = 0x1673a0a14332f140ULL;
};

template<class ContainerAllocator>
struct DataType< ::self_learning_communication::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "self_learning_communication/pose";
  }

  static const char* value(const ::self_learning_communication::pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::self_learning_communication::pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Int32 camera_id\n\
std_msgs/Time camera_timestamp\n\
geometry_msgs/Pose camera_pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Int32\n\
int32 data\n\
================================================================================\n\
MSG: std_msgs/Time\n\
time data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::self_learning_communication::pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::self_learning_communication::pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_id);
      stream.next(m.camera_timestamp);
      stream.next(m.camera_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::self_learning_communication::pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::self_learning_communication::pose_<ContainerAllocator>& v)
  {
    s << indent << "camera_id: ";
    s << std::endl;
    Printer< ::std_msgs::Int32_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_id);
    s << indent << "camera_timestamp: ";
    s << std::endl;
    Printer< ::std_msgs::Time_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_timestamp);
    s << indent << "camera_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SELF_LEARNING_COMMUNICATION_MESSAGE_POSE_H
