// Generated by gencpp from file self_learning_communication/secret_code.msg
// DO NOT EDIT!


#ifndef SELF_LEARNING_COMMUNICATION_MESSAGE_SECRET_CODE_H
#define SELF_LEARNING_COMMUNICATION_MESSAGE_SECRET_CODE_H

#include <ros/service_traits.h>


#include <self_learning_communication/secret_codeRequest.h>
#include <self_learning_communication/secret_codeResponse.h>


namespace self_learning_communication
{

struct secret_code
{

typedef secret_codeRequest Request;
typedef secret_codeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct secret_code
} // namespace self_learning_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::self_learning_communication::secret_code > {
  static const char* value()
  {
    return "4808b418c9da88e8e5bd0ad4c2770375";
  }

  static const char* value(const ::self_learning_communication::secret_code&) { return value(); }
};

template<>
struct DataType< ::self_learning_communication::secret_code > {
  static const char* value()
  {
    return "self_learning_communication/secret_code";
  }

  static const char* value(const ::self_learning_communication::secret_code&) { return value(); }
};


// service_traits::MD5Sum< ::self_learning_communication::secret_codeRequest> should match 
// service_traits::MD5Sum< ::self_learning_communication::secret_code > 
template<>
struct MD5Sum< ::self_learning_communication::secret_codeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::self_learning_communication::secret_code >::value();
  }
  static const char* value(const ::self_learning_communication::secret_codeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::self_learning_communication::secret_codeRequest> should match 
// service_traits::DataType< ::self_learning_communication::secret_code > 
template<>
struct DataType< ::self_learning_communication::secret_codeRequest>
{
  static const char* value()
  {
    return DataType< ::self_learning_communication::secret_code >::value();
  }
  static const char* value(const ::self_learning_communication::secret_codeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::self_learning_communication::secret_codeResponse> should match 
// service_traits::MD5Sum< ::self_learning_communication::secret_code > 
template<>
struct MD5Sum< ::self_learning_communication::secret_codeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::self_learning_communication::secret_code >::value();
  }
  static const char* value(const ::self_learning_communication::secret_codeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::self_learning_communication::secret_codeResponse> should match 
// service_traits::DataType< ::self_learning_communication::secret_code > 
template<>
struct DataType< ::self_learning_communication::secret_codeResponse>
{
  static const char* value()
  {
    return DataType< ::self_learning_communication::secret_code >::value();
  }
  static const char* value(const ::self_learning_communication::secret_codeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SELF_LEARNING_COMMUNICATION_MESSAGE_SECRET_CODE_H
