(cl:defpackage self_learning_communication-msg
  (:use )
  (:export
   "<MOTION_PLANNINGACTION>"
   "MOTION_PLANNINGACTION"
   "<MOTION_PLANNINGACTIONFEEDBACK>"
   "MOTION_PLANNINGACTIONFEEDBACK"
   "<MOTION_PLANNINGACTIONGOAL>"
   "MOTION_PLANNINGACTIONGOAL"
   "<MOTION_PLANNINGACTIONRESULT>"
   "MOTION_PLANNINGACTIONRESULT"
   "<MOTION_PLANNINGFEEDBACK>"
   "MOTION_PLANNINGFEEDBACK"
   "<MOTION_PLANNINGGOAL>"
   "MOTION_PLANNINGGOAL"
   "<MOTION_PLANNINGRESULT>"
   "MOTION_PLANNINGRESULT"
   "<PERSON>"
   "PERSON"
   "<POSE>"
   "POSE"
  ))

