; Auto-generated. Do not edit!


(cl:in-package self_learning_communication-msg)


;//! \htmlinclude motion_planningFeedback.msg.html

(cl:defclass <motion_planningFeedback> (roslisp-msg-protocol:ros-message)
  ((percent
    :reader percent
    :initarg :percent
    :type std_msgs-msg:Float64
    :initform (cl:make-instance 'std_msgs-msg:Float64)))
)

(cl:defclass motion_planningFeedback (<motion_planningFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <motion_planningFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'motion_planningFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name self_learning_communication-msg:<motion_planningFeedback> is deprecated: use self_learning_communication-msg:motion_planningFeedback instead.")))

(cl:ensure-generic-function 'percent-val :lambda-list '(m))
(cl:defmethod percent-val ((m <motion_planningFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader self_learning_communication-msg:percent-val is deprecated.  Use self_learning_communication-msg:percent instead.")
  (percent m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <motion_planningFeedback>) ostream)
  "Serializes a message object of type '<motion_planningFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'percent) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <motion_planningFeedback>) istream)
  "Deserializes a message object of type '<motion_planningFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'percent) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<motion_planningFeedback>)))
  "Returns string type for a message object of type '<motion_planningFeedback>"
  "self_learning_communication/motion_planningFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'motion_planningFeedback)))
  "Returns string type for a message object of type 'motion_planningFeedback"
  "self_learning_communication/motion_planningFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<motion_planningFeedback>)))
  "Returns md5sum for a message object of type '<motion_planningFeedback>"
  "2023e8040621affdd0459e82a77abec5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'motion_planningFeedback)))
  "Returns md5sum for a message object of type 'motion_planningFeedback"
  "2023e8040621affdd0459e82a77abec5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<motion_planningFeedback>)))
  "Returns full string definition for message of type '<motion_planningFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 不断反馈进度~%std_msgs/Float64 percent~%~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'motion_planningFeedback)))
  "Returns full string definition for message of type 'motion_planningFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 不断反馈进度~%std_msgs/Float64 percent~%~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <motion_planningFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'percent))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <motion_planningFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'motion_planningFeedback
    (cl:cons ':percent (percent msg))
))
