; Auto-generated. Do not edit!


(cl:in-package self_learning_communication-msg)


;//! \htmlinclude motion_planningGoal.msg.html

(cl:defclass <motion_planningGoal> (roslisp-msg-protocol:ros-message)
  ((final
    :reader final
    :initarg :final
    :type geometry_msgs-msg:Vector3
    :initform (cl:make-instance 'geometry_msgs-msg:Vector3)))
)

(cl:defclass motion_planningGoal (<motion_planningGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <motion_planningGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'motion_planningGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name self_learning_communication-msg:<motion_planningGoal> is deprecated: use self_learning_communication-msg:motion_planningGoal instead.")))

(cl:ensure-generic-function 'final-val :lambda-list '(m))
(cl:defmethod final-val ((m <motion_planningGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader self_learning_communication-msg:final-val is deprecated.  Use self_learning_communication-msg:final instead.")
  (final m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <motion_planningGoal>) ostream)
  "Serializes a message object of type '<motion_planningGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'final) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <motion_planningGoal>) istream)
  "Deserializes a message object of type '<motion_planningGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'final) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<motion_planningGoal>)))
  "Returns string type for a message object of type '<motion_planningGoal>"
  "self_learning_communication/motion_planningGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'motion_planningGoal)))
  "Returns string type for a message object of type 'motion_planningGoal"
  "self_learning_communication/motion_planningGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<motion_planningGoal>)))
  "Returns md5sum for a message object of type '<motion_planningGoal>"
  "96b55ae3c29c08040f01a834ea1b83ab")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'motion_planningGoal)))
  "Returns md5sum for a message object of type 'motion_planningGoal"
  "96b55ae3c29c08040f01a834ea1b83ab")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<motion_planningGoal>)))
  "Returns full string definition for message of type '<motion_planningGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 定义目标点~%geometry_msgs/Vector3 final~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'motion_planningGoal)))
  "Returns full string definition for message of type 'motion_planningGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 定义目标点~%geometry_msgs/Vector3 final~%~%================================================================================~%MSG: geometry_msgs/Vector3~%# This represents a vector in free space. ~%# It is only meant to represent a direction. Therefore, it does not~%# make sense to apply a translation to it (e.g., when applying a ~%# generic rigid transformation to a Vector3, tf2 will only apply the~%# rotation). If you want your data to be translatable too, use the~%# geometry_msgs/Point message instead.~%~%float64 x~%float64 y~%float64 z~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <motion_planningGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'final))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <motion_planningGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'motion_planningGoal
    (cl:cons ':final (final msg))
))
