; Auto-generated. Do not edit!


(cl:in-package self_learning_communication-msg)


;//! \htmlinclude motion_planningResult.msg.html

(cl:defclass <motion_planningResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type std_msgs-msg:Bool
    :initform (cl:make-instance 'std_msgs-msg:Bool)))
)

(cl:defclass motion_planningResult (<motion_planningResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <motion_planningResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'motion_planningResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name self_learning_communication-msg:<motion_planningResult> is deprecated: use self_learning_communication-msg:motion_planningResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <motion_planningResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader self_learning_communication-msg:result-val is deprecated.  Use self_learning_communication-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <motion_planningResult>) ostream)
  "Serializes a message object of type '<motion_planningResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'result) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <motion_planningResult>) istream)
  "Deserializes a message object of type '<motion_planningResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'result) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<motion_planningResult>)))
  "Returns string type for a message object of type '<motion_planningResult>"
  "self_learning_communication/motion_planningResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'motion_planningResult)))
  "Returns string type for a message object of type 'motion_planningResult"
  "self_learning_communication/motion_planningResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<motion_planningResult>)))
  "Returns md5sum for a message object of type '<motion_planningResult>"
  "c2420602a83d8ccc0f3664e0daafab6c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'motion_planningResult)))
  "Returns md5sum for a message object of type 'motion_planningResult"
  "c2420602a83d8ccc0f3664e0daafab6c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<motion_planningResult>)))
  "Returns full string definition for message of type '<motion_planningResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 运行结果~%std_msgs/Bool result ~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'motion_planningResult)))
  "Returns full string definition for message of type 'motion_planningResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# 运行结果~%std_msgs/Bool result ~%~%================================================================================~%MSG: std_msgs/Bool~%bool data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <motion_planningResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'result))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <motion_planningResult>))
  "Converts a ROS message object to a list"
  (cl:list 'motion_planningResult
    (cl:cons ':result (result msg))
))
